# Generated by Django 5.0.4 on 2024-05-13 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('index_e', models.CharField(max_length=12, verbose_name='Е-индекс')),
                ('description', models.TextField(verbose_name='Описание')),
                ('brix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество сухих веществ')),
                ('manufacturer', models.TextField(max_length=40, verbose_name='Производитель')),
                ('supplier', models.TextField(max_length=40, verbose_name='Поставщик')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('unit_of_measure', models.CharField(choices=[('л', 'литр'), ('кг', 'килограмм'), ('т', 'тонна'), ('шт', 'штук')], max_length=100, verbose_name='Единицы измерения')),
                ('added_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('image', models.ImageField(blank=True, default='default_image.png', upload_to='myproject/media', verbose_name='Изображение')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='IngredientGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='myproject/media/ingredient', verbose_name='Фото')),
                ('ingredient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ingredientsapp.ingredient', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Галерея ингредиентов',
            },
        ),
    ]
