# Generated by Django 5.0.4 on 2024-05-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
    ]
